### ISSUE TITLE
Waf build fail

### ISSUE THREAD

**Issue by kiririn** [mpv-player/homebrew-mpv#15]
Trying to upgrade to the newest stable version (0.3.0). OS X 10.9.1, docutils 0.11 and mpv installed with --with-bundle.

==> waf configure --prefix=/usr/local/Cellar/mpv/0.3.0 --disable-sdl --disable-x11 --
==> waf install
Waf: Leaving directory `/private/tmp/mpv-ebIg/mpv-0.3.0/build'
Build failed
 -> task in 'rst2man' failed (exit status 1): 
    {task 4505949520: rst2man mpv.rst -> mpv.1}
' /usr/local/bin/rst2man.py ../DOCS/man/en/mpv.rst DOCS/man/en/mpv.1 '

**Comment by fuzzy76** [comment]
It returned for me. :( Also, #95 seems to be a duplicate.
