### ISSUE TITLE
Libass-ct & libass

### ISSUE THREAD

**Issue by Rick74crx** [mpv-player/homebrew-mpv#42]
Libass-ct is severely outdated compared to libass, and no commits were made for over eight months. Plus, it shows heavy problems with files handled flawlessy by regular libass (e.g. FFF's releases of Jinsei, no subs rendered at all), and its use is discouraged even by mpv's devs: 
https://github.com/mpv-player/homebrew-mpv/issues/38
https://github.com/mpv-player/mpv/issues/1365
However libass-ct is still default in this' repo's formula, and its install is requested even if mpv is built with the '--with-official-libass' flag.

Isn't it possible then to switch over the regular libass as the default choice?

**Comment by niksy** [comment]
Any progress on this?

**Comment by pigoz** [comment]
Fixed in bf140d44294 like @Argon- suggested.

I merged all the new libass progress in libass-ct some weeks ago. Fontconfig is just too bad on OS X to enable it by default (it's actually worse than on Windows).
