### ISSUE TITLE
HEAD install stuck

### ISSUE THREAD

**Issue by AirPort** [mpv-player/homebrew-mpv#47]
I tried to update mpv to the latest git master using `brew reinstall --HEAD mpv` as I usually do, but the install get stuck indefinitely on the last step and I have to force homebrew to quit the install process with Ctrl+C. The problem persist even uninstalling and reinstalling the HEAD version. 
This evening it was working just fine, and no other homebrew package is giving me troubles (`brew doctor` seems fine too).

Here the verbose terminal output: https://gist.github.com/AirPort/40884503272198feed14

**Comment by Argon-** [comment]
Same for me and it's this commit: https://github.com/mpv-player/mpv/commit/e920a00ebad645cd14d341f4dabd4c5c077d2e0c but tbh I know neither why nor what's exactly happening here.

**Comment by AirPort** [comment]
As pointed out in the IRC channel, using --without-zsh-comp makes the install successful, waiting for a proper fix.

**Comment by Argon-** [comment]
Ah right, basically every help call does not exit mpv properly and zsh is parsing `--list-options` afaik.

**Comment by wm4** [comment]
Should be fixed now. Please report if there are still problems.
