### ISSUE TITLE
config file issues?

### ISSUE THREAD

**Issue by blacRose** [mpv-player/homebrew-mpv#48]
## FIXED THIS... see next
	~ brew install --HEAD mpv-player/mpv/libass-ct
	==> Installing libass-ct from mpv-player/homebrew-mpv
	==> Cloning https://github.com/pigoz/libass-ct.git
	Cloning into '/Library/Caches/Homebrew/libass-ct--git'...
	remote: Counting objects: 65, done.
	remote: Compressing objects: 100% (61/61), done.
	remote: Total 65 (delta 8), reused 19 (delta 2)
	Unpacking objects: 100% (65/65), done.
	Checking connectivity... done.
	==> Checking out branch fonts
	==> autoreconf -i
	glibtoolize: copying file 'm4/lt~obsolete.m4'
	configure.ac:34: error: possibly undefined macro: AC_DEFINE
	      If this token and others are legitimate, please use m4_pattern_allow.
	      See the Autoconf documentation.
	autoreconf: /usr/local/Cellar/autoconf/2.69/bin/autoconf failed with exit status: 1

	READ THIS: http://git.io/brew-troubleshooting
	If reporting this issue please do so at (not Homebrew/homebrew):
	  https://github.com/mpv-player/homebrew-mpv/issues

----

and...

----

	brew install mpv
	Error: No available formula for mpv
	Searching formula...
	Searching taps...

**Comment by blacRose** [comment]
Had to reinstall cask, mpv then installed but I get a bunch of config errors.

	mpv
	Error parsing option fontconfig (option not found)
	/Users/user/.mpv/config:3: setting option fontconfig='true' failed.
	Error parsing option ffactor (option not found)
	/Users/user/.mpv/config:5: setting option ffactor='10' failed.
	Error parsing option sub-bg-alpha (option not found)
	/Users/user/.mpv/config:6: setting option sub-bg-alpha='0' failed.
	Error parsing option sub-bg-color (option not found)
	/Users/user/.mpv/config:7: setting option sub-bg-color='0' failed.
	Error parsing option subfont-blur (option not found)
	/Users/user/.mpv/config:9: setting option subfont-blur='1' failed.
	Error parsing option autoq (option not found)
	/Users/user/.mpv/config:12: setting option autoq='100' failed.
	Error parsing option double (option not found)
	/Users/user/.mpv/config:14: setting option double='yes' failed.
	mpv 0.7.3-git-c4e4d9c (C) 2000-2015 mpv/MPlayer/mplayer2 projects
	 built on 2015-01-28T10:14:00
	ffmpeg library versions:
	   libavutil       54.15.100
	   libavcodec      56.13.100
	   libavformat     56.15.102
	   libswscale      3.1.101
	   libavfilter     5.2.103
	   libswresample   1.1.100

	Usage:   mpv [options] [url|path/]filename

	Basic options:
	 --start=<time>    seek to given (percent, seconds, or hh:mm:ss) position
	 --no-audio        do not play sound
	 --no-video        do not play video
	 --fs              fullscreen playback
	 --sub-file=<file> specify subtitle file to use
	 --playlist=<file> specify playlist file

	 --list-options    list all mpv options

----

## My config file is:
	# Write your default config options here!

	fontconfig=true
	osd-font="Calibri"
	ffactor="10" #black outline
	sub-bg-alpha="0" #background color ala closed captions
	sub-bg-color="0" #black to white
	sub-scale="3.7"	#truetype font scaling
	subfont-blur=1 #Slight blur

	#This sets the postprocessing into overdrive using all possible spare cpu cycles to make the movie look better
	autoq=100
	vf=pp=de,hqdn3d
	double="yes"	#double buffering(recommended for subtitles)
	monitoraspect="16:10"	#I'm on a widescreen laptop so keeps 4:3 content from stretching

**Comment by AirPort** [comment]
That config file seems to me like an old mplayer's one. Many of those options have been changed, renamed or removed, and mpv can't clearly parse them. See:

```
Error parsing option fontconfig (option not found)
/Users/user/.mpv/config:3: setting option fontconfig='true' failed.
Error parsing option ffactor (option not found)
/Users/user/.mpv/config:5: setting option ffactor='10' failed.
Error parsing option sub-bg-alpha (option not found)
/Users/user/.mpv/config:6: setting option sub-bg-alpha='0' failed.
Error parsing option sub-bg-color (option not found)
/Users/user/.mpv/config:7: setting option sub-bg-color='0' failed.
Error parsing option subfont-blur (option not found)
/Users/user/.mpv/config:9: setting option subfont-blur='1' failed.
Error parsing option autoq (option not found)
/Users/user/.mpv/config:12: setting option autoq='100' failed.
Error parsing option double (option not found)
/Users/user/.mpv/config:14: setting option double='yes' failed.
```

**Comment by wm4** [comment]
>fontconfig=true

This is the default.

>ffactor="10" #black outline

Removed, not sure about replacement.

>sub-bg-alpha="0" #background color ala closed captions
>sub-bg-color="0" #black to white

``--sub-text-back-color``, I think.

>subfont-blur=1 #Slight blur

There is ``--osd-blur`` and ``--sub-text-blur`` (for OSD and subtitles).

>#This sets the postprocessing into overdrive using all possible spare cpu cycles to make the movie look better
>autoq=100
>vf=pp=de,hqdn3d

Very questionable. I doubt it makes it look actually better. These look like recommendations from 2004. ``pp`` is still available via ``vf=lavfi[pp=de]``, but I doubt you actually want it.

>double="yes"    #double buffering(recommended for subtitles)

This is the default, you can't even disable it (because it makes no sense).

>monitoraspect="16:10"   #I'm on a widescreen laptop so keeps 4:3 content from stretching

This can lead to video being stretched incorrectly, why do you even set it? Normally it doesn't need to.

**Comment by Argon-** [comment]
`hqdn3d` is a denoiser, in other words it's killing detail. `de` is not even the "high quality" pp preset but merely "default". I'm pretty sure you don't want either of them.
If you want go to for "high quality" in mpv you want to take a look at `vo=opengl-hq`. More details here: http://mpv.io/manual/master/#video-output-drivers-opengl

**Comment by blacRose** [comment]
Oops. How can I close this?
