### ISSUE TITLE
outdated cask?

### ISSUE THREAD

**Issue by aeosynth** [mpv-player/homebrew-mpv#52]
i'm new to casks (only enabled it for this project), and the latest mpv version i see is `0.7.3`. is there an updated cask?

**Comment by Argon-** [comment]
Yes, the Cask is outdated, however it is not maintained here but "directly" in the Cask repo (https://github.com/caskroom/homebrew-cask/blob/master/Casks/mpv.rb).
You don't need Cask to build and use mpv. The .app bundle is afaik linked to `/Applications`.

**Comment by pigoz** [comment]
closing this, the cask is not maintained by us.
