### ISSUE TITLE
waf ftp is down

### ISSUE THREAD

**Issue by hghtmes** [mpv-player/homebrew-mpv#53]
homebrew seems to point to a dead link when I run 'brew reinstall --HEAD --with-official-libass mpv'

**Comment by genoma** [comment]
```
curl: (7) Failed to connect to ftp.waf.io port 80: Connection refused
Error: Failed to download resource "mpv--waf"
Download failed: http://ftp.waf.io/pub/release/waf-1.8.4
```

Building from sources it downloads `waf` from another source as a fallback:

```
Downloading http://ftp.waf.io/pub/release/waf-1.8.4...
Download failed.
Downloading http://www.freehackers.org/~tnagy/release/waf-1.8.4...
Checksum verified.
```

**Comment by c4ligari** [comment]
Changing "http://" to "ftp://" in the formula works for me and is probably better than using the backup mirror...

**Comment by aktau** [comment]
> I don't think it's actually offline: changing "http://" to "ftp://" in the formula works for me and is probably better than using the backup mirror... made a pull request.

Perhaps even that was a glitch:

```
==> Downloading ftp://ftp.waf.io/pub/release/waf-1.8.4

curl: (9) Server denied you to change to the given directory
Error: Failed to download resource "mpv--waf"
Download failed: ftp://ftp.waf.io/pub/release/waf-1.8.4
```
