### ISSUE TITLE
mpv failed to upgrade on 10.10.3

### ISSUE THREAD

**Issue by alexbepple** [mpv-player/homebrew-mpv#59]
The upgrade attempt fails as follows:

```
❯❯❯ brew upgrade mpv
==> Upgrading 1 outdated package, with result:
mpv 0.9.0
==> Upgrading mpv
==> Downloading https://github.com/mpv-player/mpv/archive/v0.9.0.tar.gz
Already downloaded: /Library/Caches/Homebrew/mpv-0.9.0.tar.gz
==> Downloading https://pypi.python.org/packages/source/d/docutils/docutils-0.11
Already downloaded: /Library/Caches/Homebrew/mpv--docutils-0.11.tar.gz
==> python setup.py install --prefix=/usr/local/Cellar/mpv/0.9.0/libexec
==> Downloading http://ftp.waf.io/pub/release/waf-1.8.4
Already downloaded: /Library/Caches/Homebrew/mpv--waf-1.8.4
==> python waf configure --prefix=/usr/local/Cellar/mpv/0.9.0 --enable-zsh-comp
Checking for libguess support                                             : no ('libguess >= 1.0' not found)
Checking for Samba support                                                : no ('smbclient' not found)
Checking for Lua                                                          : yes (version found: 52)
Checking for SSA/ASS support                                              : no ('libass >= 0.12.1' not found)
Unable to find development files for libass, or the version found is too old. Aborting. If you really mean to compile without libass support use --disable-libass.
{…}
``` 

The troubleshooting information according to <https://git.io/brew-troubleshooting>
is at <https://gist.github.com/17ed9313c3dc679addda>.

`brew info` is misleading as it says that all the required dependencies are installed:
```
❯❯❯ brew info mpv
mpv: stable 0.9.0, HEAD
https://github.com/mpv-player/mpv
/usr/local/Cellar/mpv/0.7.2 (339 files, 27M) *
  Built from source
From: https://github.com/mpv-player/homebrew-mpv/blob/master/Formula/mpv.rb
==> Dependencies
Build: pkg-config ✔
Required: mpv-player/mpv/libass-ct ✔, ffmpeg ✔
Recommended: mpg123 ✔, jpeg ✔, little-cms2 ✔, lua ✔
Optional: libcaca ✘, libbs2b ✘, libdvdread ✘, libdvdnav ✘, libbluray ✘, libaacs ✘, vapoursynth ✘
{…}
```

**Comment by wm4** [comment]
For the record, I'm pretty sure that the libass version requirement was bumped since 0.7.2.

**Comment by henry0312** [comment]
yeah, check the below error message:

```
Unable to find development files for libass, or the version found is too old. Aborting. If you really mean to compile without libass support use --disable-libass.
```

**Comment by xiongchiamiov** [comment]
I'm running into this despite having `libass` installed, at a version supposedly accepted:

    [$]> brew info libass
    libass: stable 0.12.1 (bottled)
    [snip]
    [$]> brew upgrade mpv
    ==> Upgrading 1 outdated package, with result:
    mpv 0.9.0
    [snip]
    Checking for SSA/ASS support                                              : no ('libass >= 0.12.1' not found)

**Comment by xiongchiamiov** [comment]
Ah, I found the issue (or mine, at least):

I had at some point in the past installed `libass-ct` from this repo.  Since its version is marked as `HEAD`, it doesn't get automatically upgraded, so it was hanging out at some version that was older than 0.12.1, and **it** was getting looked at by mpv's configure script.

So, doing a `brew reinstall --HEAD libass-ct` to update that first got things working.

**Comment by henry0312** [comment]
If you want to use official libass, I guess you have to build it with harfbuzz (but I'm not sure :p

**Comment by alexbepple** [comment]
I want it to just work, for a nice user experience. ;)

My intention when submitting the issue was not to find a fix. Sure, I can reinstall libass-ct. But I think I should not need to. The submitted the issue so the maintainers could figure out why the upgrade attempt does not go smoothly.

**Comment by wm4** [comment]
>If you want to use official libass, I guess you have to build it with harfbuzz (but I'm not sure :p

It should work without too (but don't if you want to watch Arabic subs or such). The main problem with official libass is fontconfig, which can take a long time to scan the fonts.

**Comment by Argon-** [comment]
> I submitted the issue so the maintainers could figure out why the upgrade attempt does not go smoothly.

Because brew does not support updating HEAD formulas (yet). Working around this is inherently a bit "hacky" imo.
