### ISSUE TITLE
Latest is 0.9.0 when 0.9.1 is out

### ISSUE THREAD

**Issue by Naio** [mpv-player/homebrew-mpv#60]
Homebrew currently says that 0.9.0 is the latest stable release even though 0.9.1 is out. Is there some kind of waiting/grace period before you change the release Homebrew will install?

**Comment by Argon-** [comment]
Someone has to update the homebrew formula by hand for each new version. Just be patient.

**Comment by Naio** [comment]
Alright, thanks!
