### ISSUE TITLE
harfbuzz

### ISSUE THREAD

**Issue by lepture** [mpv-player/homebrew-mpv#63]
homebrew has built-in harfbuzz now

**Comment by pigoz** [comment]
Their version depends on cairo which requires x11.

**Comment by zanderzhng** [comment]
Cairo can actually install with '--without-x11' option, but keeping this harfbuzz with less dependencies should be fine.

**Comment by Argon-** [comment]
But when your formula triggers the installation of harfbuzz which in turn triggers cairo, X11 will be installed. There is afaik no way to communicate `--without-x11`, that's why a local version of the formula was created.
