### ISSUE TITLE
FFmpeg with ssl

### ISSUE THREAD

**Issue by sCreami** [mpv-player/homebrew-mpv#65]
First, thank you for your formula. I couldn't build mpv without its help.
So I was trying to play a YouTube video with mpv when I realised that I couldn't because YouTube forces the url through https and ffmpeg was lacking the ssl capability.

So I asked myself.. Why don't they build ffmpeg with OpenSSL by default in their formula ?
Because It would just need to add an option on line 25 and it would greatly help newbies like me.

>depends_on 'ffmpeg' => 'with-openssl'
https://github.com/mpv-player/homebrew-mpv/blob/master/Formula/mpv.rb#L25

But maybe there are philosophical aspects that I didn't know ?

**Comment by pigoz** [comment]
I didn't have this problem, maybe because I installed openssl separately, or is homebrew picking up the system one? (who knows)

I think you have a valid point though...

**Comment by wm4** [comment]
Note that ffmpeg git master now has native support for the OSX SSL API, which is enabled by default in raw ffmpeg at least.

**Comment by pigoz** [comment]
Oh I see, that may be why. I have ffmpeg git master installed.

**Comment by sCreami** [comment]
So there's no need to add this option. Just waiting.
Thanks.
