### ISSUE TITLE
mpv fails to install on OS X 10.10.4

### ISSUE THREAD

**Issue by yuureiu** [mpv-player/homebrew-mpv#71]
Using homebrew, the installs appears to fail on the last step. I have included the entire install log, but the only error appears to be when it is trying to perform the final step. It complains about a folder not being writeable. I am not sure if it is failing to set permissions, or if I need to set something manually.

----------------------------------------------------------------------------------------------------------------------------------------

MacBook-Pro:~ yuurei$ brew tap mpv-player/mpv
==> Tapping mpv-player/mpv
Cloning into '/usr/local/Library/Taps/mpv-player/homebrew-mpv'...
remote: Counting objects: 9, done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 9 (delta 0), reused 4 (delta 0), pack-reused 0
Unpacking objects: 100% (9/9), done.
Checking connectivity... done.
Tapped 5 formulae (36 files, 148K)
MacBook-Pro:~ yuurei$ brew install mpv
==> Installing mpv from mpv-player/homebrew-mpv
==> Installing dependencies for mpv-player/mpv/mpv: pkg-config, autoconf,
==> Installing mpv-player/mpv/mpv dependency: pkg-config
==> Downloading https://homebrew.bintray.com/bottles/pkg-config-0.28.yosemite.bo
######################################################################## 100.0%
==> Pouring pkg-config-0.28.yosemite.bottle.2.tar.gz
🍺  /usr/local/Cellar/pkg-config/0.28: 10 files, 612K
==> Installing mpv-player/mpv/mpv dependency: autoconf
==> Downloading https://homebrew.bintray.com/bottles/autoconf-2.69.yosemite.bott
######################################################################## 100.0%
==> Pouring autoconf-2.69.yosemite.bottle.1.tar.gz
🍺  /usr/local/Cellar/autoconf/2.69: 70 files, 3.1M
==> Installing mpv-player/mpv/mpv dependency: automake
==> Downloading https://homebrew.bintray.com/bottles/automake-1.15.yosemite.bott
######################################################################## 100.0%
==> Pouring automake-1.15.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/automake/1.15: 130 files, 3.2M
==> Installing mpv-player/mpv/mpv dependency: libtool
==> Downloading https://homebrew.bintray.com/bottles/libtool-2.4.6.yosemite.bott
######################################################################## 100.0%
==> Pouring libtool-2.4.6.yosemite.bottle.tar.gz
==> Caveats
In order to prevent conflicts with Apple's own libtool we have prepended a "g"
so, you have instead: glibtool and glibtoolize.
==> Summary
🍺  /usr/local/Cellar/libtool/2.4.6: 69 files, 3.8M
==> Installing mpv-player/mpv/mpv dependency: yasm
==> Downloading https://homebrew.bintray.com/bottles/yasm-1.3.0.yosemite.bottle.
######################################################################## 100.0%
==> Pouring yasm-1.3.0.yosemite.bottle.1.tar.gz
🍺  /usr/local/Cellar/yasm/1.3.0: 44 files, 3.4M
==> Installing mpv-player/mpv/mpv dependency: libpng
==> Downloading https://homebrew.bintray.com/bottles/libpng-1.6.18.yosemite.bott
######################################################################## 100.0%
==> Pouring libpng-1.6.18.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/libpng/1.6.18: 17 files, 1.2M
==> Installing mpv-player/mpv/mpv dependency: freetype
==> Downloading https://homebrew.bintray.com/bottles/freetype-2.6_1.yosemite.bot
######################################################################## 100.0%
==> Pouring freetype-2.6_1.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/freetype/2.6_1: 60 files, 2.6M
==> Installing mpv-player/mpv/mpv dependency: fribidi
==> Downloading https://homebrew.bintray.com/bottles/fribidi-0.19.6.yosemite.bot
######################################################################## 100.0%
==> Pouring fribidi-0.19.6.yosemite.bottle.1.tar.gz
🍺  /usr/local/Cellar/fribidi/0.19.6: 60 files, 480K
==> Installing mpv-player/mpv/mpv dependency: gettext
==> Downloading https://homebrew.bintray.com/bottles/gettext-0.19.5.1.yosemite.b
######################################################################## 100.0%
==> Pouring gettext-0.19.5.1.yosemite.bottle.tar.gz
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local.

OS X provides the BSD gettext library and some software gets confused if both are in the library path.

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/gettext/lib
    CPPFLAGS: -I/usr/local/opt/gettext/include

==> Summary
🍺  /usr/local/Cellar/gettext/0.19.5.1: 1921 files, 22M
==> Installing mpv-player/mpv/mpv dependency: libffi
==> Downloading https://homebrew.bintray.com/bottles/libffi-3.0.13.yosemite.bott
######################################################################## 100.0%
==> Pouring libffi-3.0.13.yosemite.bottle.tar.gz
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local.

Some formulae require a newer version of libffi.

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/libffi/lib

==> Summary
🍺  /usr/local/Cellar/libffi/3.0.13: 14 files, 412K
==> Installing mpv-player/mpv/mpv dependency: glib
==> Downloading https://homebrew.bintray.com/bottles/glib-2.44.1.yosemite.bottle
######################################################################## 100.0%
==> Pouring glib-2.44.1.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/glib/2.44.1: 416 files, 18M
==> Installing mpv-player/mpv/mpv dependency: fontconfig
==> Downloading https://homebrew.bintray.com/bottles/fontconfig-2.11.1.yosemite.
######################################################################## 100.0%
==> Pouring fontconfig-2.11.1.yosemite.bottle.3.tar.gz
==> /usr/local/Cellar/fontconfig/2.11.1/bin/fc-cache -frv
🍺  /usr/local/Cellar/fontconfig/2.11.1: 448 files, 3.6M
==> Installing mpv-player/mpv/mpv dependency: pixman
==> Downloading https://homebrew.bintray.com/bottles/pixman-0.32.6.yosemite.bott
######################################################################## 100.0%
==> Pouring pixman-0.32.6.yosemite.bottle.2.tar.gz
🍺  /usr/local/Cellar/pixman/0.32.6: 11 files, 1.4M
==> Installing mpv-player/mpv/mpv dependency: cairo
==> Downloading https://homebrew.bintray.com/bottles/cairo-1.14.2_1.yosemite.bot
######################################################################## 100.0%
==> Pouring cairo-1.14.2_1.yosemite.bottle.2.tar.gz
🍺  /usr/local/Cellar/cairo/1.14.2_1: 111 files, 6.1M
==> Installing mpv-player/mpv/mpv dependency: icu4c
==> Downloading https://homebrew.bintray.com/bottles/icu4c-55.1.yosemite.bottle.
######################################################################## 100.0%
==> Pouring icu4c-55.1.yosemite.bottle.tar.gz
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local.

OS X provides libicucore.dylib (but nothing else).

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/icu4c/lib
    CPPFLAGS: -I/usr/local/opt/icu4c/include

==> Summary
🍺  /usr/local/Cellar/icu4c/55.1: 244 files, 66M
==> Installing mpv-player/mpv/mpv dependency: gobject-introspection
==> Downloading https://homebrew.bintray.com/bottles/gobject-introspection-1.44.
######################################################################## 100.0%
==> Pouring gobject-introspection-1.44.0.yosemite.bottle.2.tar.gz
🍺  /usr/local/Cellar/gobject-introspection/1.44.0: 196 files, 10M
==> Installing mpv-player/mpv/mpv dependency: harfbuzz
==> Downloading https://homebrew.bintray.com/bottles/harfbuzz-1.0.1.yosemite.bot
######################################################################## 100.0%
==> Pouring harfbuzz-1.0.1.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/harfbuzz/1.0.1: 79 files, 3.5M
==> Installing mpv-player/mpv/mpv dependency: mpv-player/mpv/libass-ct
==> Cloning https://github.com/pigoz/libass-ct.git
Cloning into '/Library/Caches/Homebrew/libass-ct--git'...
remote: Counting objects: 65, done.
remote: Compressing objects: 100% (61/61), done.
remote: Total 65 (delta 9), reused 18 (delta 2), pack-reused 0
Unpacking objects: 100% (65/65), done.
Checking connectivity... done.
==> Checking out branch fonts
==> autoreconf -i
==> ./configure --disable-fontconfig --prefix=/usr/local/Cellar/libass-ct/HEAD
==> make install
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local.

This is a drop in replacement of libass. It uses the same pkg-config
package name: it's better not to install it to avoid breaking other
packages in homebrew.

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/libass-ct/lib
    CPPFLAGS: -I/usr/local/opt/libass-ct/include

==> Summary
🍺  /usr/local/Cellar/libass-ct/HEAD: 9 files, 436K, built in 17 seconds
==> Installing mpv-player/mpv/mpv dependency: x264
==> Downloading https://homebrew.bintray.com/bottles/x264-r2533.yosemite.bottle.
######################################################################## 100.0%
==> Pouring x264-r2533.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/x264/r2533: 9 files, 3.4M
==> Installing mpv-player/mpv/mpv dependency: lame
==> Downloading https://homebrew.bintray.com/bottles/lame-3.99.5.yosemite.bottle
######################################################################## 100.0%
==> Pouring lame-3.99.5.yosemite.bottle.1.tar.gz
🍺  /usr/local/Cellar/lame/3.99.5: 25 files, 2.1M
==> Installing mpv-player/mpv/mpv dependency: libvo-aacenc
==> Downloading https://homebrew.bintray.com/bottles/libvo-aacenc-0.1.3.yosemite
######################################################################## 100.0%
==> Pouring libvo-aacenc-0.1.3.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/libvo-aacenc/0.1.3: 15 files, 336K
==> Installing mpv-player/mpv/mpv dependency: xvid
==> Downloading https://homebrew.bintray.com/bottles/xvid-1.3.4.yosemite.bottle.
######################################################################## 100.0%
==> Pouring xvid-1.3.4.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/xvid/1.3.4: 9 files, 1.3M
==> Installing mpv-player/mpv/mpv dependency: ffmpeg
==> Downloading https://homebrew.bintray.com/bottles/ffmpeg-2.7.2.yosemite.bottl
######################################################################## 100.0%
==> Pouring ffmpeg-2.7.2.yosemite.bottle.tar.gz
==> Caveats
FFmpeg has been built without libfaac for licensing reasons;
libvo-aacenc is used by default.
To install with libfaac, you can:
  brew reinstall ffmpeg --with-faac

You can also use the experimental FFmpeg encoder, libfdk-aac, or
libvo_aacenc to encode AAC audio:
  ffmpeg -i input.wav -c:a aac -strict experimental output.m4a
Or:
  brew reinstall ffmpeg --with-fdk-aac
  ffmpeg -i input.wav -c:a libfdk_aac output.m4a
==> Summary
🍺  /usr/local/Cellar/ffmpeg/2.7.2: 206 files, 43M
==> Installing mpv-player/mpv/mpv dependency: mpg123
==> Downloading https://homebrew.bintray.com/bottles/mpg123-1.22.2.yosemite.bott
######################################################################## 100.0%
==> Pouring mpg123-1.22.2.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/mpg123/1.22.2: 16 files, 656K
==> Installing mpv-player/mpv/mpv dependency: jpeg
==> Downloading https://homebrew.bintray.com/bottles/jpeg-8d.yosemite.bottle.2.t
######################################################################## 100.0%
==> Pouring jpeg-8d.yosemite.bottle.2.tar.gz
🍺  /usr/local/Cellar/jpeg/8d: 18 files, 776K
==> Installing mpv-player/mpv/mpv dependency: libtiff
==> Downloading https://homebrew.bintray.com/bottles/libtiff-4.0.4.yosemite.bott
######################################################################## 100.0%
==> Pouring libtiff-4.0.4.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/libtiff/4.0.4: 257 files, 3.9M
==> Installing mpv-player/mpv/mpv dependency: little-cms2
==> Downloading https://homebrew.bintray.com/bottles/little-cms2-2.7.yosemite.bo
######################################################################## 100.0%
==> Pouring little-cms2-2.7.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/little-cms2/2.7: 16 files, 1.1M
==> Installing mpv-player/mpv/mpv dependency: lua
==> Downloading https://homebrew.bintray.com/bottles/lua-5.2.4_1.yosemite.bottle
######################################################################## 100.0%
==> Pouring lua-5.2.4_1.yosemite.bottle.tar.gz
==> Caveats
Please be aware due to the way Luarocks is designed any binaries installed
via Luarocks-5.2 AND 5.1 will overwrite each other in /usr/local/bin.

This is, for now, unavoidable. If this is troublesome for you, you can build
rocks with the `--tree=` command to a special, non-conflicting location and
then add that to your `$PATH`.
==> Summary
🍺  /usr/local/Cellar/lua/5.2.4_1: 81 files, 1.1M
==> Installing mpv-player/mpv/mpv
==> Downloading https://github.com/mpv-player/mpv/archive/v0.9.2.tar.gz
==> Downloading from https://codeload.github.com/mpv-player/mpv/tar.gz/v0.9.2
######################################################################## 100.0%
==> Downloading https://pypi.python.org/packages/source/d/docutils/docutils-0.11
######################################################################## 100.0%
==> python setup.py install --prefix=/usr/local/Cellar/mpv/0.9.2/libexec
==> Downloading https://waf.io/waf-1.8.12
######################################################################## 100.0%
==> python waf configure --prefix=/usr/local/Cellar/mpv/0.9.2 --enable-zsh-comp
==> python waf install
==> creating a OS X Application bundle
==> python TOOLS/osxbundle.py build/mpv
==> Caveats
mpv.app installed to:
  /usr/local/Cellar/mpv/0.9.2

To link the application to a normal Mac OS X location:
    brew linkapps
or:
    ln -s /usr/local/Cellar/mpv/0.9.2/mpv.app /Applications

zsh completion has been installed to:
  /usr/local/share/zsh/site-functions

.app bundles were installed.
Run `brew linkapps mpv` to symlink these to /Applications.
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink share/zsh/site-functions/_mpv
/usr/local/share/zsh/site-functions is not writable.

You can try again using:
  brew link mpv
==> Summary
🍺  /usr/local/Cellar/mpv/0.9.2: 324 files, 12M, built in 23 seconds

----------------------------------------------------------------------------------------------------------------------------------------

MacBook-Pro:~ yuurei$ brew link mpv
Linking /usr/local/Cellar/mpv/0.9.2... 
Error: Could not symlink share/zsh/site-functions/_mpv
/usr/local/share/zsh/site-functions is not writable.

**Comment by Argon-** [comment]
Well the error is written right there. Fix the permissions of /usr/local/share/zsh/site-functions and it should work. Maybe run brew doctor, he should detect this problem and supply you with the necessary commands to fix it.

**Comment by yuureiu** [comment]
Thanks for the help. sudo chown -R $(whoami) ./site-functions . and re-running brew link mpv worked fine.
