### ISSUE TITLE
Failed to update mpv with optional dependencies

### ISSUE THREAD

**Issue by mrcotter** [mpv-player/homebrew-mpv#73]
The error can be seen as following:

<img width="896" alt="qq20150904-2 2x" src="https://cloud.githubusercontent.com/assets/5259084/9682718/a16e1518-534c-11e5-8694-63749a8112ba.png">

It relates to python version problems. I'm running OS X Yosemite 10.10.5, and python 2 is the build-in version while python 3 is installed by homebrew.

**Comment by AirPort** [comment]
It probably has something to to with a conflict between this https://github.com/Homebrew/homebrew/commit/85271644b0083cbc0fd6fea71120d1ad859fbc2a and the mpv formula in the repo.
For the time being I just manually reverted the python_requirement.rb file to a previous version, but it's quite an unorthodox measure wating for a real fix.

**Comment by henry0312** [comment]
Hello.
Can you try master's HEAD?

**Comment by AirPort** [comment]
That solved the problem on my end. Thank you!

**Comment by outlyer** [comment]
In regards to @mrcotter saying that "python3 is installed by homebrew," I just want to note that it *can* be installed by Homebrew, but certainly isn't required and for those of us who are using Homebrew to manage our Python installation's, switching to Python 3.x is a pretty big change. 

I was able to build and install mpv  after removing all the python3 references from the formula so may I propose that python3 becomes a *vapoursynth* dependency instead? 

i.e. in the formula

```ruby
if build.with? 'official-libass'
  depends_on :python3
end
```

and use the default (Homebrew or OSX) python for everyone else?

**Comment by Argon-** [comment]
Python is not just needed for vapoursynth but also for mpv's build system waf.

**Comment by mrcotter** [comment]
Updated formula works fine. Thanks!

However, I encountered another bug yesterday which may come from the newest build of mpv itself. I have to disable hardware decoding when using opengl-hq, otherwise the video output would be nothing but black...

**Comment by henry0312** [comment]
> That solved the problem on my end. Thank you!
https://github.com/mpv-player/homebrew-mpv/issues/73#issuecomment-138984977

> Updated formula works fine. Thanks!
https://github.com/mpv-player/homebrew-mpv/issues/73#issuecomment-139423754

I'm glad to hear that.

**Comment by outlyer** [comment]
@Argon- I think that makes sense; most people are still on Python 2.x and unless they explicitly need 3.x for vapoursynth, it'd be better to just use the installed version. But python itself should still be a dependency of course, just not versioned.
