### ISSUE TITLE
Config file for best quality, CPU usage does not matter

### ISSUE THREAD

**Issue by Daniyal-Javani** [mpv-player/homebrew-mpv#74]
Hello
Excuse me, Could you please help me to config mpv for best quality (CPU/GPU usage does not matter), after lots of googling I set the config file, but I'm not sure it's best.
Hardware:
CPU: Ci3
GPU: intel hd3000 (without any other graphic card)
Ram = 4 GB
```
##################
# video settings #
##################

# Specify default video driver (see --vo=help for a list).
vo=opengl-hq:dither-depth=16:scale=ewa_lanczossharp

# Software scaling
sws-scaler=lanczos

# Video filters
vf=hqdn3d=2:2:3,yadif=,scale=:768,lavfi=pp

# Deinterlacing
deinterlace=yes

# Start in fullscreen mode by default.
fs=yes

##################
# audio settings #
##################

# Specify default audio driver (see --ao=help for a list).
ao=pulse

# Change subtitle encoding. For Arabic subtitles use 'cp1256'.
# If the file seems to be valid UTF-8, prefer UTF-8.
sub-codepage=utf8:cp1256

# Addicitional settings!
vd-lavc-threads=4
monitorpixelaspect=1
osd-scale=1
no-sub-ass
sub-scale=0.5
cache=4096
index=default
audio-channels=2
af-add=scaletempo
softvol=yes
softvol-max=110
```

Best regards

**Comment by Argon-** [comment]
>dither-depth=16

This makes no sense in most cases.

>sws-scaler

Probably the worst thing you can do. You have already specified a scaling algorithm in your VO, why again specifying a different one?

>vf=hqdn3d=2:2:3,yadif=,scale=:768,lavfi=pp

Same. hqdn3d is a denoiser, as in: it removes detail from your video. yadif is a deinterlacer, not needed on non-interlaced content and let's not even talk about post processing (pp). Better remove the whole line.

As VO, put there `vo=opengl-hq:scale=ewa_lanczossharp:cscale=ewa_lanczossoft:tscale=mitchell:temporal-dither:blend-subtitles:pbo:target-prim=bt.709:target-trc=bt.1886:gamma-auto:icc-profile-auto:3dlut-size=256x256x256:source-shader=<path/to/deband.glsl>` and you are good.
In case this doesn't work on your hardware use your current: `vo=opengl-hq:scale=ewa_lanczossharp:source-shader=<path/to/deband.glsl>`.
Get deband.glsl [here](https://github.com/haasn/gentoo-conf/blob/nanodesu/home/nand/.mpv/shaders/deband.glsl).

**Comment by Daniyal-Javani** [comment]
Thank you so much @Argon- .
