### ISSUE TITLE
brew doctor reports libass-git as missing after installing with official libass.

### ISSUE THREAD

**Issue by Zegnat** [mpv-player/homebrew-mpv#82]
After installing mpv using the following settings, `brew doctor` tells me I am missing `libass-git`.

```
brew install mpv --with-official-libass --with-libaacs
```

But I thought `libass-git` wasn’t required when the `--with-official-libass` build flag was used?

Is this because of a problem with the mpv formula, or simply a limitations of `brew doctor` that might have to be escalated to Homebrew?

**Comment by pigoz** [comment]
Probably a brew doctor issue, anyway I just removed libass-git. Since yesterday's release libass stable (0.13.0) has all the features we wan in OS X.
