### ISSUE TITLE
brew install mpv failed

### ISSUE THREAD

**Issue by ljian1992** [mpv-player/homebrew-mpv#84]
how to fixed it?

info 
==> Installing mpv from mpv-player/homebrew-mpv
==> Downloading https://github.com/mpv-player/mpv/archive/v0.10.0.tar.gz
Already downloaded: /Library/Caches/Homebrew/mpv-0.10.0.tar.gz
==> Downloading https://pypi.python.org/packages/source/d/docutils/docutils-0.12
Already downloaded: /Library/Caches/Homebrew/mpv--docutils-0.12.tar.gz
==> python3 setup.py install --prefix=/usr/local/Cellar/mpv/0.10.0/libexec
==> Downloading https://waf.io/waf-1.8.12
Already downloaded: /Library/Caches/Homebrew/mpv--waf-1.8.12
==> python3 waf configure --prefix=/usr/local/Cellar/mpv/0.10.0 --enable-zsh-com
==> python3 waf install
Waf: Leaving directory `/private/tmp/mpv20151002-9282-1yxjvwd/mpv-0.10.0/build'
Build failed
 -> task in 'rst2man' failed (exit status 1):
	{task 4327405272: rst2man mpv.rst -> mpv.1}
' /usr/local/Cellar/mpv/0.10.0/libexec/bin/rst2man.py ../DOCS/man/mpv.rst DOCS/man/mpv.1 '

**Comment by Argon-** [comment]
https://github.com/mpv-player/homebrew-mpv/issues/83
