### ISSUE TITLE
Cannot upgrade to version 0.11.0

### ISSUE THREAD

**Issue by Kitefr** [mpv-player/homebrew-mpv#86]
Hello,

I tried to update to the last version as i had the version 0.9.2 installed but encountered an error.
```
==> Upgrading mpv-player/mpv/mpv
==> Downloading https://github.com/mpv-player/mpv/archive/v0.11.0.tar.gz
Already downloaded: /Library/Caches/Homebrew/mpv-0.11.0.tar.gz
==> Downloading https://pypi.python.org/packages/source/d/docutils/docutils-0.12.tar.gz
Already downloaded: /Library/Caches/Homebrew/mpv--docutils-0.12.tar.gz
==> python3 setup.py install --prefix=/usr/local/Cellar/mpv/0.11.0/libexec
Last 15 lines from /Users/yannschmidt/Library/Logs/Homebrew/mpv/01.python3:
2015-10-12 10:04:39 +0200

python3
setup.py
install
--prefix=/usr/local/Cellar/mpv/0.11.0/libexec


READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/mpv-player/homebrew-mpv/issues
```
As i can see, it tried to installed python 3 but i already have it, using pyenv. 
An idea to help me solve this problem ?

Thanks.

**Comment by meritozh** [comment]
use python3 via homebrew instead of pyenv

**Comment by pigoz** [comment]
Well I don't that's an option if someone is using python for work (I work with ruby and could not do without rbenv). Sadly I have no idea how to solve this problem.

**Comment by meritozh** [comment]
I don't think using pyenv to manage versions of python is a good method. I have faced too much bugs when i compiler something which need python supporting when i use pyenv, such as ycm, vim, etc. Everytime i must edit makefile.

**Comment by Kitefr** [comment]
Well, i couldn't find a solution to installing it from Howebrew.
So i deleted it completely and installed the application package from the official website.
Sorry for the inconvenience ! Thanks.

**Comment by pigoz** [comment]
Just to let you know I just pushed some changes the might fix the issues with pyenv.
