### ISSUE TITLE
brew install mpv failed

### ISSUE THREAD

**Issue by dong2590** [mpv-player/homebrew-mpv#90]
dependency has lost , how to fixed it ?

$ brew install mpv
==> Installing mpv from mpv-player/homebrew-mpv
==> Installing dependencies for mpv: xz, pkg-config, readline, sqlite, gd
==> Installing mpv dependency: xz
==> Downloading http://fossies.org/linux/misc/xz-5.0.7.tar.bz2

curl: (22) The requested URL returned error: 410 Gone
Trying a mirror...
==> Downloading http://tukaani.org/xz/xz-5.0.7.tar.bz2

curl: (22) The requested URL returned error: 403 Forbidden
Error: Failed to download resource "xz"
Download failed: http://tukaani.org/xz/xz-5.0.7.tar.bz2

**Comment by Argon-** [comment]
That has to be fixed by homebrew

**Comment by pigoz** [comment]
Use `brew update`. Your Homebrew is outdated.
