### ISSUE TITLE
no module named setuptools

### ISSUE THREAD

**Issue by KCAS** [mpv-player/homebrew-mpv#97]
![screen shot 2015-12-26 at 10 47 11](https://cloud.githubusercontent.com/assets/7694114/12004977/62cd2520-abc0-11e5-9e7b-98161f894580.png)

getting this on latest update.

**Comment by pigoz** [comment]
Where is your python3 from?

Does `python3 -c 'import setuptools'` from console work?

**Comment by KCAS** [comment]
@pigoz
python3 mainly from homebrew repo. 

did what you suggested and it did not prompt anything or any error, and my installation proceeded completely. although i uninstalled and cleaned homebrew a while ago.

thanks you and merry christmas!

**Comment by pigoz** [comment]
Glad it worked. Merry Christmas.
